### PR TITLE
feat: add cosmere initiative system

### PR DESCRIPTION
**Pull request by jsc17**
Never got around to creating an issue for this.

Overrides Foundry's default initiative rolling system to use the Cosmere RPGs slow/fast popcorn style initiative system. Implements a bucket/phases system to group combatants based on turn speed and whether they are a player character or an adversary. Defaults all combatants to slow turn speed when they are added to the combat. Added buttons to the combat tracker allowing them to switch turn speed and indicate they have acted for the turn, and set some basic styling for the combat-tracker template.

Done: 
* Create flags on combatant creation to store turn speed and activation status, defaulting to slow for the turn speed.
* Set initiative based on turn speed/character type, instead of rolling
* Add buttons to combat tracker to switch turn speed and indicate the character has activated for the turn (using default foundry icons as placeholders)
* Add headers to the combat tracker to sort player/npc turns (Fast Players, Fast NPCs, etc ...)
* Add context menu option to combat tracker combatants to reset activation status

To Do:
* Localization

### CODE REVIEW

**Comment by stanavdb** [comment]
Since there are still changes listed as to do, I have converted this PR to a draft, to make tracking what needs to be reviewed easier. Once its done feel free to mark it as Ready for review.

**Comment by jsc17** [comment]
I mainly left the todo's there as a note. We are currently waiting on brotherwise to supply us with some approved icons, so I'm just going to remove the todo's and create a separate issue to update the icons when they are available. The initiative tracker is fully functional at this point.

**Comment by jsc17** [comment]
Converting back to draft because I saw that the release 0.1.0 branch has localization. Going to build against that and then will mark for review.

**Comment by jsc17** [comment]
Closing to create a new PR from with correct branches

**Pull request closed without merging**
